type: google.api.Service
config_version: 3

http:
  rules:
    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ListEntities
      get: /api/v1/entities

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.CountEntities
      get: /api/v1/entities/count

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.GetEntity
      get: /api/v1/entity/{key}

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.GetEntityHistory
      get: /api/v1/entity/{key}/history

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ListOperations
      get: /api/v1/operations

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.CountOperations
      get: /api/v1/operations/count

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.GetOperation
      get: /api/v1/operation/{tx_hash}/{op_index}

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.AddressStats
      get: /api/v1/address/{address}/stats

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ListBiggestSpenders
      get: /api/v1/leaderboard/biggest-spenders

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.BlockStats
      get: /api/v1/block/{block_number}/stats

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ListEntitiesByBtl
      get: /api/v1/leaderboard/entities-by-btl

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ListAddressByEntitiesOwned
      get: /api/v1/leaderboard/entities-owned

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ListLargestEntities
      get: /api/v1/leaderboard/largest-entities

    #################### Health ####################

    - selector: blockscout.golemBaseIndexer.v1.Health.Check
      get: /health
