type: google.api.Service
config_version: 3

http:
  rules:
    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.GetEntity
      get: /api/v1/entities/{key}

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.CountOperations
      get: /api/v1/operations/count

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.GetOperation
      get: /api/v1/operations/{tx_hash}/{index}

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ListEntities
      get: /api/v1/entities

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ListOperations
      get: /api/v1/operations

    #################### Health ####################

    - selector: blockscout.golemBaseIndexer.v1.Health.Check
      get: /health
