type: google.api.Service
config_version: 3

http:
  rules:
    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ListEntities
      get: /api/v1/entities

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.CountEntities
      get: /api/v1/entities/count

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.EntitiesAverages
      get: /api/v1/entities/averages

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.GetEntity
      get: /api/v1/entity/{key}

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.GetEntityHistory
      get: /api/v1/entity/{key}/history

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ListOperations
      get: /api/v1/operations

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.CountOperations
      get: /api/v1/operations/count

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.GetOperation
      get: /api/v1/operation/{tx_hash}/{op_index}

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.AddressStats
      get: /api/v1/address/{address}/stats

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.BlockStats
      get: /api/v1/block/{block_number}/stats

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ListCustomContractTransactions
      get: /api/v1/transactions/custom-contract

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.AddressLeaderboardRanks
      get: /api/v1/address/{address}/leaderboard-ranks

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.GetConsensusInfo
      get: /api/v1/chain/consensus-info

    # Leaderboards

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.LeaderboardBiggestSpenders
      get: /api/v1/leaderboard/biggest-spenders

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.LeaderboardTopAccounts
      get: /api/v1/leaderboard/top-accounts

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.LeaderboardEntitiesCreated
      get: /api/v1/leaderboard/entities-created

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.LeaderboardEntitiesOwned
      get: /api/v1/leaderboard/entities-owned

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.LeaderboardDataOwned
      get: /api/v1/leaderboard/data-owned

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.LeaderboardLargestEntities
      get: /api/v1/leaderboard/largest-entities

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.LeaderboardEffectivelyLargestEntities
      get: /api/v1/leaderboard/effectively-largest-entities

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.LeaderboardEntitiesByBtl
      get: /api/v1/leaderboard/entities-by-btl

    # Charts

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ChartDataUsage
      get: /api/v1/chart/data-usage

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ChartStorageForecast
      get: /api/v1/chart/storage-forecast

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.GetEntityDataHistogram # FIXME naming
      get: /api/v1/chart/entity-data-histogram

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ChartOperationCount
      get: /api/v1/chart/operation-count

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ChartBlockTransactions
      get: /api/v1/chart/block-transactions

    - selector: blockscout.golemBaseIndexer.v1.GolemBaseIndexerService.ChartBlockOperations
      get: /api/v1/chart/block-operations

    #################### Health ####################

    - selector: blockscout.golemBaseIndexer.v1.Health.Check
      get: /health
