//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "optimism_children_l3_chains")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub chain_id: i64,
    #[sea_orm(unique)]
    pub chain_name: String,
    #[sea_orm(column_type = "Text")]
    pub l3_rpc_url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub l3_rpc_url_fallback: Option<String>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub l3_message_passer: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub l3_standard_bridge: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub l2_portal_address: Vec<u8>,
    pub l3_batch_size: i32,
    pub l3_last_indexed_block: i64,
    pub l3_latest_block: Option<i64>,
    pub l3_latest_block_updated_at: Option<DateTime>,
    pub enabled: bool,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::optimism_children_l3_deposits::Entity")]
    OptimismChildrenL3Deposits,
}

impl Related<super::optimism_children_l3_deposits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OptimismChildrenL3Deposits.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
