//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "optimism_children_l3_deposits")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub chain_id: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub block_hash: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub tx_hash: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub source_hash: Vec<u8>,
    pub success: bool,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::optimism_children_l3_chains::Entity",
        from = "Column::ChainId",
        to = "super::optimism_children_l3_chains::Column::ChainId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OptimismChildrenL3Chains,
}

impl Related<super::optimism_children_l3_chains::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OptimismChildrenL3Chains.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
