//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::{
    addresses::Entity as Addresses, blocks::Entity as Blocks, logs::Entity as Logs,
    optimism_children_pending_logs::Entity as OptimismChildrenPendingLogs,
    optimism_children_transaction_deposited_events::Entity as OptimismChildrenTransactionDepositedEvents,
    transactions::Entity as Transactions,
};
