//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::{
    addresses::Entity as Addresses, blocks::Entity as Blocks, logs::Entity as Logs,
    optimism_children_pending_logs::Entity as OptimismChildrenPendingLogs,
    transactions::Entity as Transactions,
};
