//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "blocks")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub hash: Vec<u8>,
    pub number: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::golem_base_operations::Entity")]
    GolemBaseOperations,
}

impl Related<super::golem_base_operations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GolemBaseOperations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
