//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use super::sea_orm_active_enums::{GolemBaseEntityStatusType, GolemBaseOperationType};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "golem_base_entity_history")]
pub struct Model {
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub entity_key: Vec<u8>,
    pub block_number: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub block_hash: Vec<u8>,
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub transaction_hash: Vec<u8>,
    pub tx_index: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub op_index: i64,
    pub block_timestamp: DateTime,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub owner: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub prev_owner: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub sender: Vec<u8>,
    pub operation: GolemBaseOperationType,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub data: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub prev_data: Option<Vec<u8>>,
    #[sea_orm(column_type = "Decimal(Some((21, 0)))", nullable)]
    pub btl: Option<Decimal>,
    pub status: GolemBaseEntityStatusType,
    pub prev_status: Option<GolemBaseEntityStatusType>,
    pub expires_at_block_number: Option<i64>,
    pub prev_expires_at_block_number: Option<i64>,
    pub content_type: Option<String>,
    pub prev_content_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::blocks::Entity",
        from = "Column::BlockHash",
        to = "super::blocks::Column::Hash",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Blocks,
    #[sea_orm(
        belongs_to = "super::golem_base_operations::Entity",
        from = "(Column::TransactionHash, Column::OpIndex)",
        to = "(super::golem_base_operations::Column::TransactionHash, super::golem_base_operations::Column::Index)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GolemBaseOperations,
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::TransactionHash",
        to = "super::transactions::Column::Hash",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Transactions,
}

impl Related<super::blocks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Blocks.def()
    }
}

impl Related<super::golem_base_operations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GolemBaseOperations.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
