//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use super::sea_orm_active_enums::GolemBaseEntityStatusType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "golem_base_entities")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub hash: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub data: Vec<u8>,
    pub status: GolemBaseEntityStatusType,
    pub created_at: i32,
    pub expires_at: i32,
    pub last_updated_at: i32,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::golem_base_numeric_annotations::Entity")]
    GolemBaseNumericAnnotations,
    #[sea_orm(has_many = "super::golem_base_string_annotations::Entity")]
    GolemBaseStringAnnotations,
}

impl Related<super::golem_base_numeric_annotations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GolemBaseNumericAnnotations.def()
    }
}

impl Related<super::golem_base_string_annotations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GolemBaseStringAnnotations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
