//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use super::sea_orm_active_enums::GolemBaseEntityStatusType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "golem_base_entities")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub key: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub data: Option<Vec<u8>>,
    pub status: GolemBaseEntityStatusType,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub owner: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub creator: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub created_at_tx_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub last_updated_at_tx_hash: Vec<u8>,
    pub expires_at_block_number: Option<i64>,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
    pub content_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::golem_base_numeric_annotations::Entity")]
    GolemBaseNumericAnnotations,
    #[sea_orm(has_many = "super::golem_base_string_annotations::Entity")]
    GolemBaseStringAnnotations,
}

impl Related<super::golem_base_numeric_annotations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GolemBaseNumericAnnotations.def()
    }
}

impl Related<super::golem_base_string_annotations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GolemBaseStringAnnotations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
