//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "golem_base_numeric_annotations")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub entity_hash: Vec<u8>,
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub operation_txhash: Vec<u8>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub operation_index: i32,
    pub active: bool,
    #[sea_orm(column_type = "Text")]
    pub key: String,
    #[sea_orm(column_type = "Decimal(Some((21, 0)))")]
    pub value: Decimal,
    pub inserted_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::golem_base_entities::Entity",
        from = "Column::EntityHash",
        to = "super::golem_base_entities::Column::Hash",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GolemBaseEntities,
    #[sea_orm(
        belongs_to = "super::golem_base_operations::Entity",
        from = "(Column::OperationTxhash, Column::OperationIndex)",
        to = "(super::golem_base_operations::Column::TransactionHash, super::golem_base_operations::Column::Index)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GolemBaseOperations,
}

impl Related<super::golem_base_entities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GolemBaseEntities.def()
    }
}

impl Related<super::golem_base_operations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GolemBaseOperations.def()
    }
}

impl Related<super::golem_base_string_annotations::Entity> for Entity {
    fn to() -> RelationDef {
        super::golem_base_operations::Relation::GolemBaseStringAnnotations.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::golem_base_operations::Relation::GolemBaseNumericAnnotations
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
