//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use super::sea_orm_active_enums::GolemBaseOperationType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "golem_base_operations")]
pub struct Model {
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub entity_key: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub sender: Vec<u8>,
    pub operation: GolemBaseOperationType,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub data: Option<Vec<u8>>,
    #[sea_orm(column_type = "Decimal(Some((21, 0)))", nullable)]
    pub btl: Option<Decimal>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub block_hash: Vec<u8>,
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub transaction_hash: Vec<u8>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub index: i64,
    pub inserted_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::golem_base_numeric_annotations::Entity")]
    GolemBaseNumericAnnotations,
    #[sea_orm(has_many = "super::golem_base_string_annotations::Entity")]
    GolemBaseStringAnnotations,
}

impl Related<super::golem_base_numeric_annotations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GolemBaseNumericAnnotations.def()
    }
}

impl Related<super::golem_base_string_annotations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GolemBaseStringAnnotations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
