//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::{
    addresses::Entity as Addresses, blocks::Entity as Blocks,
    golem_base_entities::Entity as GolemBaseEntities,
    golem_base_entity_history::Entity as GolemBaseEntityHistory,
    golem_base_entity_locks::Entity as GolemBaseEntityLocks,
    golem_base_numeric_annotations::Entity as GolemBaseNumericAnnotations,
    golem_base_operations::Entity as GolemBaseOperations,
    golem_base_pending_logs_operations::Entity as GolemBasePendingLogsOperations,
    golem_base_pending_transaction_cleanups::Entity as GolemBasePendingTransactionCleanups,
    golem_base_pending_transaction_operations::Entity as GolemBasePendingTransactionOperations,
    golem_base_string_annotations::Entity as GolemBaseStringAnnotations, logs::Entity as Logs,
    transactions::Entity as Transactions,
};
