//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "transactions")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub hash: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub to_address_hash: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::golem_base_pending_transaction_operations::Entity")]
    GolemBasePendingTransactionOperations,
}

impl Related<super::golem_base_pending_transaction_operations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GolemBasePendingTransactionOperations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
