swagger: "2.0"
info:
  title: v1/golem-base-indexer.proto
  version: version not set
tags:
  - name: GolemBaseIndexerService
  - name: Health
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/entities:
    get:
      operationId: GolemBaseIndexerService_ListEntities
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListEntitiesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - GolemBaseIndexerService
  /api/v1/entities/{key}:
    get:
      operationId: GolemBaseIndexerService_GetEntity
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1Entity'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: key
          in: path
          required: true
          type: string
      tags:
        - GolemBaseIndexerService
  /api/v1/operations:
    get:
      operationId: GolemBaseIndexerService_ListOperations
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListOperationsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - GolemBaseIndexerService
  /api/v1/operations/{tx_hash}/{index}:
    get:
      operationId: GolemBaseIndexerService_GetOperation
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1Operation'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: tx_hash
          in: path
          required: true
          type: string
        - name: index
          in: path
          required: true
          type: string
          format: uint64
      tags:
        - GolemBaseIndexerService
  /health:
    get:
      summary: |-
        If the requested service is unknown, the call will fail with status
        NOT_FOUND.
      operationId: Health_Check
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1HealthCheckResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: service
          in: query
          required: false
          type: string
      tags:
        - Health
definitions:
  HealthCheckResponseServingStatus:
    type: string
    enum:
      - UNKNOWN
      - SERVING
      - NOT_SERVING
      - SERVICE_UNKNOWN
    default: UNKNOWN
    description: ' - SERVICE_UNKNOWN: Used only by the Watch method.'
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1Entity:
    type: object
    properties:
      key:
        type: string
      data:
        type: string
        title: FIXME some raw data type maybe?
      status:
        $ref: '#/definitions/v1EntityStatus'
      created_at_tx_hash:
        type: string
      last_updated_at_tx_hash:
        type: string
      expires_at_block_number:
        type: string
        format: uint64
  v1EntityStatus:
    type: string
    enum:
      - Active
      - Deleted
      - Expired
    default: Active
  v1HealthCheckResponse:
    type: object
    properties:
      status:
        $ref: '#/definitions/HealthCheckResponseServingStatus'
  v1ListEntitiesResponse:
    type: object
    properties:
      items:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Entity'
        title: FIXME add pagination metadata
  v1ListOperationsResponse:
    type: object
    properties:
      items:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Operation'
        title: FIXME add pagination metadata
  v1Operation:
    type: object
    properties:
      entity_key:
        type: string
      sender:
        type: string
      operation:
        $ref: '#/definitions/v1OperationType'
      data:
        type: string
        title: FIXME some raw data type maybe?
      btl:
        type: string
        format: uint64
      block_hash:
        type: string
      transaction_Hash:
        type: string
      index:
        type: string
        format: uint64
  v1OperationType:
    type: string
    enum:
      - Create
      - Update
      - Delete
      - Extend
    default: Create
